/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.kazurayam.gradleplugins.filediff

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 *
 */
class FileDiffPlugin implements Plugin<Project> {
    @Override
    void apply(Project project) {
        project.extensions.create('fileDiff', FileDiffExtension)
        // Register a task
        project.tasks.register("fileDiff", FileDiffTask) {
            file1 = project.fileDiff.file1
            file2 = project.fileDiff.file2
        }
    }
}
