plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id 'maven-publish'
    id 'base'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

group = 'com.kazurayam'
version = '0.2.0'

base {
    archivesName = 'file-diff-plugin'
}

dependencies {
    // Use the awesome Spock testing and specification framework
    testImplementation libs.spock.core
    // Junit dependencies
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testLogging {
        events "started", "passed", "skipped", "failed"
    }
}

gradlePlugin {
    // Define the plugin
    plugins {
        fileDiff {
            id = 'com.kazurayam.file-diff'
            implementationClass = 'com.kazurayam.gradleplugins.filediff.FileDiffPlugin'
        }
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = "${base.archivesName}"
        }
    }
}